"""create_regional_covid_data_table

Revision ID: b3950e4eee58
Revises: 
Create Date: 2025-05-10 13:13:04.678778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3950e4eee58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regional_covid_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('total_positive_cases', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_date', 'region_name', name='_submission_date_region_name_uc')
    )
    op.create_index(op.f('ix_regional_covid_data_id'), 'regional_covid_data', ['id'], unique=False)
    op.create_index(op.f('ix_regional_covid_data_region_code'), 'regional_covid_data', ['region_code'], unique=False)
    op.create_index(op.f('ix_regional_covid_data_region_name'), 'regional_covid_data', ['region_name'], unique=False)
    op.create_index(op.f('ix_regional_covid_data_submission_date'), 'regional_covid_data', ['submission_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regional_covid_data_submission_date'), table_name='regional_covid_data')
    op.drop_index(op.f('ix_regional_covid_data_region_name'), table_name='regional_covid_data')
    op.drop_index(op.f('ix_regional_covid_data_region_code'), table_name='regional_covid_data')
    op.drop_index(op.f('ix_regional_covid_data_id'), table_name='regional_covid_data')
    op.drop_table('regional_covid_data')
    # ### end Alembic commands ###
